### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by xSavior-of-God** [eliotest98/VanillaChallenges#11]
- [x] Rimuovere in ogni file di challenge il config `Start: '5:00'`
```yaml
...
  TimeSettings:
    # What time do you want the challenge to start?
    Start: '5:00'
...
```
- [x] Creare nel `config.yml` l'opzione di settaggio del scheduler che definisce l'orario in cui deve essere chiamata la next challenge:
```yaml
...
  Scheduler:
    Enable: true
    # 24h format
    Time: "05:00"
...
```

**Esempio di esecuzione:**

**1:** 05:00 21-11-2022
**2:** 05:00 22-11-2022
***Ops tra la 2 e la 3 il server ha avuto un problema, si è spento alle 00:00 e si è riavviato alle 12:00 del 23-11***
**3:** 12:00 23-11-2022
**4:** 05:00 24-11-2022

Vedi tu come farlo per gestire l'archiviazione della data di scadenza (*si scadenza, ciò significa che fai 1 controllo di lettura della data attuale e vedi se è maggiore di quella di scadenza, si? se si rigeneri la nuova data di scadenza con il giorno successivo a quello attuale con l'orario specificato dall'utente*)
